theme = "tokyo"

[editor]
auto-completion = false
completion-replace = true
idle-timeout = 0
bufferline = "multiple"
line-number = "relative"
shell = ["nu", "-c"]

[editor.statusline]
left = ["mode", "spinner", "file-base-name", "read-only-indicator", "file-modification-indicator"]
center = ["file-type"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert.j]
k = ["normal_mode", "collapse_selection", "keep_primary_selection"]

